#!/bin/sh -e

gcc -Wall -Wextra -Werror -pedantic -fsanitize=undefined -O3 -g test.c -o kokoro-test && \
	valgrind --leak-check=full ./kokoro-test
clang -Wall -Wextra -Werror -pedantic -fsanitize=undefined -O3 -g test.c -o kokoro-test && \
	valgrind --leak-check=full ./kokoro-test
