#!/bin/sh -e

FLAGS="-Wall -Wextra -Werror -pedantic -fno-sanitize-recover=undefined -fsanitize=undefined -fsanitize=address -O3 -g"

gcc ${FLAGS} test.c -o kokoro-test && ASAN_OPTIONS="suppressions=asan.supp" ./kokoro-test
clang ${FLAGS} test.c -o kokoro-test && ASAN_OPTIONS="replace_intrin=0,suppressions=asan.supp" ./kokoro-test
